{% set name = "lume-gpt" %}
{% set version = "0.9.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: b3d01220c4b5c25b19e85d88e63f01845f2f61ea2e1cf47fa3217e436c7f0817

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9,<3.13
    - setuptools
    - pip
  run:
    - python >=3.9,<3.13
    - h5py
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - openpmd-beamphysics
    - pyyaml
    - distgen

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT

extra:
  recipe-maintainers:
    - ColwynGulliford
