{% set name = "lume-gpt" %}
{% set version = "0.7.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 77678dd988491377d9e4615029c7fe6f90eb0dc1b738a6075fdfe0d3b4651be5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - matplotlib-base
    - numpy
    - scipy
    - openpmd-beamphysics
    - pyyaml
    - distgen

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT
extra:
  recipe-maintainers:
    - ColwynGulliford
