{% set name = "lume-gpt" %}
{% set version = "0.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8d821005483213675bdf0b5e29189cd0bb563ecfc4fe1ec2f78e41fdea72d25f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - h5py
    - matplotlib-base
    - numpy
    - scipy
    - openpmd-beamphysics
    - pyyaml
    - distgen

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: APACHE-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT
extra:
  recipe-maintainers:
    - ColwynGulliford
