{% set name = "lume-gpt" %}
{% set version = "0.9.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 795aa1aacd3fe53d9f41c6383c37b3b36935c0b8a1d8984cc029557c61f39c6e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - h5py
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - openpmd-beamphysics
    - pyyaml
    - distgen

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT

extra:
  recipe-maintainers:
    - ColwynGulliford
